spring:
  application:
    name: cf-springboot-postgress
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:/db/migration
    schemas: postgres
    baselineOnMigrate: true
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
    url: ${vcap.services.postgresql-db.credentials.uri}
    username: ${vcap.services.postgresql-db.credentials.username}
    password: ${vcap.services.postgresql-db.credentials.password}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

logging:
  level:
    root: info

